### ISSUE TITLE
Issue with text property resulting in NaNrem

### ISSUE THREAD

**Issue by kevpye-fabdata** [nicolas-cusan/tailwind-clamp#6]
Hi there,

Thanks for your work on this. We are just doing some testing with the plugin and have come across an issue when using this with the text property.

We tried it like this:

```html
<section class="w-full clamp-[text,lg,3xl]">
    ....
</section>
```

Out text variables in tailwind css for the two values above are:

```css
    --text-lg: calc(1.125rem * var(--text-scaling));
    --text-lg--line-height: calc(calc(1.75 / 1.125) * var(--text-scaling));
    --text-3xl: calc(1.875rem * var(--text-scaling));
    --text-3xl--line-height: calc(calc(2.25 / 1.875) * var(--text-scaling));
```

Both in tailwind intellisene in VS Code and the resultant CSS output in the browser we get NANrem as the values as shown below:

```css
.clamp-\[text\,lg\,3xl\] {
    font-size: clamp(NaNrem, NaNrem + NaNvw, NaNrem);
    line-height: clamp(NaNrem, NaNrem + NaNvw, NaNrem);
}
```

Are we doing something wrong or is this a bug?

**Comment by nicolas-cusan** [comment]
Hi @kevpye-fabdata sorry for my late reply. 

I guess that the plugin is not able to resolve the calculation because of the custom `--text-scaling` variable. Maybe this needs to be given as context to the plugin somehow, not sure yet how that could look. 

For the moment, I am afraid this will never work unless the `calc` statements contain only plain values.

I will look into it when I have some time and maybe not this in a "limitations" section in the readme.

**Comment by Neonsy** [comment]
I'm currently trying to figure out why

```tsx
<span className='clamp-[text,base,3xl,@md,@5xl]'>{section.name}</span>
```

with

```css
@import 'tailwindcss';
@plugin "tailwind-clamp";

:root {
    @theme {
        --color-body-main: #09090b;
        --color-header-main: #1c1c2b;

        --color-primary: #3493ff;
        --color-secondary: #d946ef;
        --color-npc: #22c55e;
        --color-guide: #f59e0b;
        --color-community: #ef4444;

        --color-github: #8b6cb3;
        --color-discord: #5865f2;
        --color-kofi: #ff5e5b;
    }

    @theme {
        /* Extra Small Devices (Portrait Phones) */
        --breakpoint-xs: 20rem; /* 320px */

        /* Small Devices (Landscape Phones, Small Tablets) */
        --breakpoint-sm: 40rem; /* 640px - Tailwind Default */

        /* Medium Devices (Tablets, Small Laptops) */
        --breakpoint-md: 48rem; /* 768px - Tailwind Default */

        /* Large Devices (Laptops, Desktops) */
        --breakpoint-lg: 64rem; /* 1024px - Tailwind Default */

        /* Extra Large Devices (Large Laptops, Desktops) */
        --breakpoint-xl: 80rem; /* 1280px - Tailwind Default */

        /* 2X Large Devices (Full HD Desktops) */
        --breakpoint-2xl: 96rem; /* 1536px - Tailwind Default */

        /* 3X Large Devices (QHD/2K Monitors) */
        --breakpoint-3xl: 120rem; /* 1920px */

        /* 4X Large Devices (WQHD/2K+ Monitors) */
        --breakpoint-4xl: 160rem; /* 2560px */

        /* 5X Large Devices (4K Monitors) */
        --breakpoint-5xl: 240rem; /* 3840px */
    }
}

```

changes that text inside the span between At 448px and 1024px
